### ISSUE TITLE
ERROR :: Runner: Function backup failed with: Bogus data given. No message_type: summmary found

### ISSUE THREAD

**Issue by chrispersonal** [netinvent/npbackup#100]
Getting a stacktrace dump in the .log files after a successful backup. This is happening consistently after each successful backup. Detailed .log output below. Relevant details:
* npbackup v3.0.0-rc6-pub-3.11-x64 WINDOWS
* TaskScheduler checks every 4 hours if backup is necessary
*  .conf file has 2 repos specified as part of the `default_group`, this is passed to npbackup via "`-c "npbackup.conf" --group-operation backup --repo-group default_group --run-as-cli`"

```
2024-10-05 08:28:55,010 :: INFO :: npbackup v3.0.0-rc6-pub-3.11-x64 2024091601 - Copyright (C) 2022-2024 NetInvent running as ...\Christopher
2024-10-05 08:28:55,315 :: INFO :: Loaded config 287FAFF4 in C:\...\npbackup.conf
2024-10-05 08:28:55,350 :: INFO :: No extra information for repos default found
2024-10-05 08:28:55,351 :: INFO :: No extra information for repos DrivePool found
2024-10-05 08:28:55,532 :: INFO :: Running group operations for repos: default, DrivePool
2024-10-05 08:28:55,628 :: INFO :: Running backup for repo default
2024-10-05 08:28:55,718 :: INFO :: Searching for a backup newer than 1 day, 0:00:00 ago
2024-10-05 08:28:58,881 :: INFO :: Snapshots listed successfully
2024-10-05 08:28:58,900 :: INFO :: No recent backup found in repo default. Newest is from 2024-10-04 08:28:52.799142-04:00
2024-10-05 08:28:58,901 :: INFO :: Runner took 3.183395 seconds for has_recent_snapshot
2024-10-05 08:28:58,910 :: INFO :: Running backup of ['C:/.../Documents'] to repo default
2024-10-05 08:28:59,690 :: INFO :: Using VSS snapshot to backup
2024-10-05 08:35:36,259 :: INFO :: Backend finished with success
2024-10-05 08:35:36,338 :: INFO :: Processed 122.4 MB of data
2024-10-05 08:35:36,339 :: INFO :: Operation finished with success
2024-10-05 08:35:36,351 :: INFO :: Runner took 400.722508 seconds for backup
2024-10-05 08:35:36,351 :: INFO :: Finished backup for repo default
2024-10-05 08:35:36,367 :: ERROR :: Runner: Function backup failed with: Bogus data given. No message_type: summmary found
2024-10-05 08:35:36,367 :: ERROR :: Trace:
Traceback (most recent call last):
  File "C:\...\NPBACK~1\npbackup\core\runner.py", line 640, in wrapper
  File "C:\...\NPBACK~1\npbackup\core\runner.py", line 442, in wrapper
  File "C:\...\NPBACK~1\npbackup\core\runner.py", line 412, in wrapper
  File "C:\...\NPBACK~1\npbackup\core\runner.py", line 1604, in group_runner
  File "C:\...\NPBACK~1\npbackup\core\runner.py", line 86, in metric_writer
  File "C:\...\NPBACK~1\npbackup\restic_metrics\__init__.py", line 194, in restic_json_to_prometheus
ValueError: Bogus data given. No message_type: summmary found
2024-10-05 08:35:36,377 :: ERROR :: Program interrupted by error: 'NoneType' object has no attribute 'put'
2024-10-05 08:35:36,377 :: INFO :: Trace:
Traceback (most recent call last):
  File "C:\...\NPBACK~1\npbackup\core\runner.py", line 640, in wrapper
  File "C:\...\NPBACK~1\npbackup\core\runner.py", line 442, in wrapper
  File "C:\...\NPBACK~1\npbackup\core\runner.py", line 412, in wrapper
  File "C:\...\NPBACK~1\npbackup\core\runner.py", line 1604, in group_runner
  File "C:\...\NPBACK~1\npbackup\core\runner.py", line 86, in metric_writer
  File "C:\...\NPBACK~1\npbackup\restic_metrics\__init__.py", line 194, in restic_json_to_prometheus
ValueError: Bogus data given. No message_type: summmary found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\...\NPBACK~1\npbackup\__main__.py", line 676, in main
  File "C:\...\NPBACK~1\npbackup\__main__.py", line 662, in cli_interface
  File "C:\...\NPBACK~1\npbackup\runner_interface.py", line 60, in entrypoint
  File "C:\...\NPBACK~1\ofunctions\threading\__init__.py", line 112, in wrapper
  File "C:\...\NPBACK~1\npbackup\core\runner.py", line 652, in wrapper
AttributeError: 'NoneType' object has no attribute 'put'
2024-10-05 08:35:36,412 :: INFO :: ExecTime = 0:06:41.418828, finished, state is: errors.
```

**Comment by deajan** [comment]
Related to #98 
I'll fix this once I finished coding the new task gui, probably next week.

Thanks for reporting.

**Comment by deajan** [comment]
New RC released including the fix.
