### ISSUE TITLE
'dict' object has no attribute 'path'

### ISSUE THREAD

**Issue by madic-creates** [netinvent/npbackup#112]
When viewing a snapshot via the "See content" button from the GUI, I get the following error:

```
2024-12-30 15:26:53,493 :: CRITICAL :: GUI Execution error 'dict' object has no attribute 'path'
2024-12-30 15:26:53,493 :: INFO :: Trace:
Traceback (most recent call last):
  File "/home/mne-adm/Downloads/npbackup-gui/npbackup/gui/__main__.py", line 1171, in main_gui
  File "/home/mne-adm/Downloads/npbackup-gui/npbackup/gui/__main__.py", line 1069, in _main_gui
  File "/home/mne-adm/Downloads/npbackup-gui/npbackup/gui/__main__.py", line 381, in ls_window
  File "/home/mne-adm/Downloads/npbackup-gui/concurrent/futures/_base.py", line 439, in result
  File "/home/mne-adm/Downloads/npbackup-gui/concurrent/futures/_base.py", line 391, in __get_result
  File "/home/mne-adm/Downloads/npbackup-gui/ofunctions/threading/__init__.py", line 95, in call_with_future
  File "/home/mne-adm/Downloads/npbackup-gui/npbackup/gui/__main__.py", line 212, in _make_treedata_from_json
AttributeError: 'dict' object has no attribute 'path'
2024-12-30 15:26:53,517 :: INFO :: ExecTime = 0:00:46.417519, finished, state is: critical.
```

Example output from a file from the log:

```
{"name":"locallist_validator_test.py","type":"file","path":"/home/mne-adm/Git/web/tests/locallist_validator_test.py","uid":1000,"gid":1000,"size":1087,"mode":420,"permissions":"-rw-r--r--","mtime":"2023-11-09T16:25:14.432162184+01:00","atime":"2023-11-09T16:25:14.432162184+01:00","ctime":"2023-11-09T16:25:14.432162184+01:00","inode":4013469,"message_type":"node","struct_type":"node"}
```

npbackup Version: 3.0.0-rc12
Used asset: npbackup-linux-x64-gui-public.tar.gz 
restic version: 0.17.3

Dou you need further information?

**Comment by deajan** [comment]
I definitly need more info ^^

For starters, what's your system ?
Could you re-run with --debug parameter and post the __COMPLETE__ logs ?
I also need to know if you run a pre-built executable, in that case, which one, or if you run plain python, I'll need your python version and pip freeze output.

**Comment by deajan** [comment]
I am not able to reproduce this, can you post the full logs with `--debug` to give me a better idea of what happens ? Of course you can anonymize the data ^^

**Comment by madic-creates** [comment]
I'll create the logs as soon as I'm back on my notebook. Probably tomorrow or on the weekend

**Comment by madic-creates** [comment]
Host OS: Arch Linux
Used Package from the GitHub release site: npbackup-linux-x64-gui-public.tar.gz
Version: 3.0.0.rc12

Executed the binary via npbackup-gui --log-file /tmp/npbackup.log --debug > debug.log

The logfile is around 51MB big. Do you know a service where I can upload that file?

**Comment by deajan** [comment]
Thank you for the debug logs... 
What version of Arch Linux so I can reproduce please ?

**Comment by deajan** [comment]
Okay, currently downloading 2025.01.01-x86_64 iso.
I'm pretty sure to know what happens (somehow, your system doesn't work with msgspec library, but still does load), hence npbackup will try to run the msgspec codepath and fails.
I could do an easy fix (check whether datastructure is a dict or a msgspec.struct object), but I prefer digging a bit further in order to avoid unnecessary code complexity.
I'll try to reproduce this today and keep you updated.

I did hope rc12 was the last rc before going final... But here I am :(

**Comment by deajan** [comment]
Well, non compiled version works out of the box... Looks worse than I thought. Somehow compiled version cannot load on Arch but loads on EL/Fedora/Debian alikes...

**Comment by deajan** [comment]
Found it ! There's some issue with the msgspec library that behaves differently between Python 3.9 and Python 3.12.
Building new RC tomorrow.

**Comment by deajan** [comment]
v3.0.0-rc13 is out and should correct the bug you encountered.
You may use linux or linux-legacy builds, both should work (but non legacy builds are faster).

Could you give a quick feedback perhaps ?
Thank you.

**Comment by madic-creates** [comment]
Can confirm. It's working. Thank you

**Comment by deajan** [comment]
Thank you for reporting back :)
