### ISSUE TITLE
Brain dump for v3 RC2

### ISSUE THREAD

**Issue by deajan** [netinvent/npbackup#76]
```
C:\Users\User\Downloads\npbackup-windows-x64-cli-public\npbackup-cli>npbackup-cli.exe -c c:\Users\User\Downloads\npbackup-windows-x64-gui-public\npbackup-gui\toto.conf --group-operation list --repo-group default_group
2024-07-30 14:28:57,093 :: INFO :: npbackup v3.0.0-rc2-pub-3.11-x64 2024072801 - Copyright (C) 2022-2024 NetInvent running as CUBE0\User
2024-07-30 14:28:57,093 :: INFO :: Loading configuration file c:\Users\User\Downloads\npbackup-windows-x64-gui-public\npbackup-gui\toto.conf
2024-07-30 14:28:57,123 :: INFO :: No extra information for repos default found
2024-07-30 14:28:57,154 :: INFO :: Running group operations for repos: default
2024-07-30 14:28:57,154 :: INFO :: Running list for repo default
2024-07-30 14:28:57,154 :: INFO :: Listing None objects of repo default
Fatal: invalid type
2024-07-30 14:28:58,830 :: ERROR :: Fatal: invalid type

2024-07-30 14:28:58,830 :: ERROR :: Failed to list None objects:
Fatal: invalid type

2024-07-30 14:28:58,830 :: INFO :: Runner took 1.675593 seconds for list
2024-07-30 14:28:58,830 :: ERROR :: Operation list failed for repo default
2024-07-30 14:28:58,830 :: ERROR :: Restic finished with errors.
2024-07-30 14:28:58,830 :: INFO :: Finished execution group operations
2024-07-30 14:28:58,830 :: INFO :: Runner took 1.675593 seconds for group_runner
2024-07-30 14:28:58,830 :: ERROR :: Operation finished with errors
2024-07-30 14:28:58,846 :: INFO :: ExecTime = 0:00:01.770036, finished, state is: errors.

C:\Users\User\Downloads\npbackup-windows-x64-cli-public\npbackup-cli>npbackup-cli.exe -c c:\Users\User\Downloads\npbackup-windows-x64-gui-public\npbackup-gui\toto.conf --group-operation list --repo-name __all__
2024-07-30 14:29:22,411 :: INFO :: npbackup v3.0.0-rc2-pub-3.11-x64 2024072801 - Copyright (C) 2022-2024 NetInvent running as CUBE0\User
2024-07-30 14:29:22,411 :: INFO :: Loading configuration file c:\Users\User\Downloads\npbackup-windows-x64-gui-public\npbackup-gui\toto.conf
2024-07-30 14:29:22,442 :: INFO :: No extra information for repos default found
2024-07-30 14:29:22,442 :: ERROR :: No repo with name __all__ found in config
2024-07-30 14:29:22,442 :: INFO :: Running group operations for repos: __all__
2024-07-30 14:29:22,458 :: ERROR :: Function list failed with: 'NoneType' object has no attribute 'g'
2024-07-30 14:29:22,458 :: ERROR :: Program interrupted by error: 'NoneType' object has no attribute 'g'
2024-07-30 14:29:22,458 :: INFO :: Trace:
Traceback (most recent call last):
  File "C:\Users\User\DOWNLO~1\NPBACK~3\NPBACK~1\npbackup\core\runner.py", line 602, in wrapper
  File "C:\Users\User\DOWNLO~1\NPBACK~3\NPBACK~1\npbackup\core\runner.py", line 406, in wrapper
  File "C:\Users\User\DOWNLO~1\NPBACK~3\NPBACK~1\npbackup\core\runner.py", line 380, in wrapper
  File "C:\Users\User\DOWNLO~1\NPBACK~3\NPBACK~1\npbackup\core\runner.py", line 1452, in group_runner
AttributeError: 'NoneType' object has no attribute 'g'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\DOWNLO~1\NPBACK~3\NPBACK~1\npbackup\__main__.py", line 605, in main
  File "C:\Users\User\DOWNLO~1\NPBACK~3\NPBACK~1\npbackup\__main__.py", line 591, in cli_interface
  File "C:\Users\User\DOWNLO~1\NPBACK~3\NPBACK~1\npbackup\runner_interface.py", line 51, in entrypoint
  File "C:\Users\User\DOWNLO~1\NPBACK~3\NPBACK~1\ofunctions\threading\__init__.py", line 112, in wrapper
  File "C:\Users\User\DOWNLO~1\NPBACK~3\NPBACK~1\npbackup\core\runner.py", line 616, in wrapper
  File "C:\Users\User\DOWNLO~1\NPBACK~3\NPBACK~1\npbackup\core\runner.py", line 56, in metric_writer
AttributeError: 'NoneType' object has no attribute 'g'
2024-07-30 14:29:22,474 :: INFO :: ExecTime = 0:00:00.062538, finished, state is: errors.

C:\Users\User\Downloads\npbackup-windows-x64-cli-public\npbackup-cli>npbackup-cli.exe -c c:\Users\User\Downloads\npbackup-windows-x64-gui-public\npbackup-gui\toto.conf --group-operation list --repo-name __all__
```

**Comment by deajan** [comment]
Minor problems:
--list expected an object type to list. Added an error message
--repo-name did not accept __all__. Added __all__ identifier, and also added an error message when repo name didn't exist.
