### ISSUE TITLE
CLI: Bad formatted YAML file does not create log file

### ISSUE THREAD

**Issue by deajan** [netinvent/npbackup#83]
```
2024-08-13 13:18:22,316 :: INFO :: npbackup v3.0.0-rc3-pub-3.11-x64 2024080501 - Copyright (C) 2022-2024 NetInvent running as CUBE0\Orsiris
2024-08-13 13:18:22,316 :: INFO :: Loading configuration file npb-test.conf
2024-08-13 13:18:22,347 :: ERROR :: Program interrupted by error: while scanning for the next token
found character '\t' that cannot start any token
  in "npb-test.conf", line 90, column 1
2024-08-13 13:18:22,347 :: INFO :: Trace:
Traceback (most recent call last):
  File "C:\NPBACKUP\npbackup\__main__.py", line 631, in main
  File "C:\NPBACKUP\npbackup\__main__.py", line 342, in cli_interface
  File "C:\NPBACKUP\npbackup\configuration.py", line 791, in load_config
  File "C:\NPBACKUP\npbackup\configuration.py", line 766, in _load_config_file
  File "C:\NPBACKUP\ruamel\yaml\main.py", line 451, in load
  File "C:\NPBACKUP\ruamel\yaml\constructor.py", line 114, in get_single_data
  File "C:\NPBACKUP\ruamel\yaml\composer.py", line 72, in get_single_node
  File "C:\NPBACKUP\ruamel\yaml\composer.py", line 94, in compose_document
  File "C:\NPBACKUP\ruamel\yaml\composer.py", line 130, in compose_node
  File "C:\NPBACKUP\ruamel\yaml\composer.py", line 211, in compose_mapping_node
  File "C:\NPBACKUP\ruamel\yaml\composer.py", line 130, in compose_node
  File "C:\NPBACKUP\ruamel\yaml\composer.py", line 211, in compose_mapping_node
  File "C:\NPBACKUP\ruamel\yaml\composer.py", line 130, in compose_node
  File "C:\NPBACKUP\ruamel\yaml\composer.py", line 211, in compose_mapping_node
  File "C:\NPBACKUP\ruamel\yaml\composer.py", line 106, in compose_node
  File "C:\NPBACKUP\ruamel\yaml\parser.py", line 141, in check_event
  File "C:\NPBACKUP\ruamel\yaml\parser.py", line 631, in parse_block_mapping_value
  File "C:\NPBACKUP\ruamel\yaml\scanner.py", line 1735, in check_token
  File "C:\NPBACKUP\ruamel\yaml\scanner.py", line 1775, in _gather_comments
  File "C:\NPBACKUP\ruamel\yaml\scanner.py", line 313, in fetch_more_tokens
ruamel.yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "npb-test.conf", line 90, column 1
2024-08-13 13:18:22,363 :: INFO :: ExecTime = 0:00:00.062501, finished, state is: errors.
```

**Comment by deajan** [comment]
False report, logs are actually created, but when running as system user, their location was in system32 folder.
